### ISSUE TITLE
example  custom-host of graceful-shutdown didn't handle SIGKILL but source codes said yes

### ISSUE THREAD

**Issue by tekpig** [iris-contrib/community-board#11]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [_examples](https://github.com/kataras/iris/tree/master/_examples), [Contributing File](https://github.com/iris-contrib/community-board/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue was never [posted](https://github.com/iris-contrib/community-board/issues) before.

### What version of Go are you using, minimum 1.8 (`go version`)?

1.8.1

### What version of Iris are you using?

Version 7.0.5

### What did you do?

I just ran the example code under the directory "_examples/intermediate/graceful-shutdown/custom-host/".

From the description, it said it can shut down gracefully by SIGINT. Then I went to see the implementation under the directory "core/host/". From the codes, it looks it can handle SIGKILL either.

But I tried the example again, it didn't handle SIGKILL.

### What did you expect to see?

I just want to know why it can't handle SIGKILL.

I want to put iris into docker, docker stop actually send SIGTERM and SIGKILL to the process, so I want to let iris handle the both signal to let iris can stop gracefully and do some actions about my service.

**Comment by kataras** [comment]
Hello @tekpig 

The default behavior handles `os.Interrupt` and  `os.Kill` (not all host machines are compatible with SIGTERM and SIGKILL). Your issue is good chance to add different source file to handle unix-only system signals, I will notify you here, but you're not limited by my actions, read below. 

If the interrupt handler doesn't work for you, you can disable it and do it manually with the classic way, to disable the default behavior add an `iris.WithoutInterruptHandler` option to the configuration on `Run`, i.e: 

`app.Run(iris.Addr(":8080"), iris.WithoutInterruptHandler)`.


You have access to the:

 ```go
[...]
import stdContext "context"
[...]
app.Shutdown(stdContext.Context[..])
```
as well :)

**Comment by tekpig** [comment]
Thanks for your suggestion! I will try it later.

**Comment by kataras** [comment]
I updated my answer and fix the issue, you can upgrade with `go get -u github.com/kataras/iris` and tell us the results later on, thanks for your report!

**Comment by kataras** [comment]
@tekpig  I updated my answer and fix the issue, you can upgrade with `go get -u github.com/kataras/iris` and tell us the results later on, thanks for your report!

Best regards,
