### ISSUE TITLE
StaticWeb suddenly throws 404's

### ISSUE THREAD

**Issue by Allendar** [iris-contrib/community-board#12]
Go: 1.8.3
darwin/macos
Version 7

Since commit https://github.com/kataras/iris/commit/3b403a4d31d144d024bcaf5571ce8c96567b8669 all my `StaticWeb` registered assets return 404's. When I switch to the commit before that one everything works correctly.

There's no panic occurring; just 404's.

**Comment by kataras** [comment]
Hello @Allendar , I know this, it's an expected behavior as I answered this morning on [chat](https://kataras.rocket.chat/channel/iris) too.

You're using `StaticWeb` on root "/", right?  I did replace the old solution to deal with it, with a new one more specific function for Single Page Applications, earlier today.

I'll push an example on how you can deal with it manually too (for simple tasks it takes 5 lines of code, nothing serious)

I am asleep coding these features and fixes (it's 06:21 here) so I'll be glad 
if you could give me some time to sleep first (5-6 hours) and I'll push the new, improved solution for this. 
Thank you very much!

**Comment by Allendar** [comment]
@kataras no worries! Take your time :)

I'm using these to serve my assets (`M` is the Iris Application):

```go
M.Favicon(filepath.FromSlash(config.MustGetString("paths.favicon")))
M.StaticWeb("/i", filepath.FromSlash(config.MustGetString("paths.images")))
M.StaticWeb("/c", filepath.FromSlash(storeAssetsPath+"/CSS"))
M.StaticWeb("/j", filepath.FromSlash(storeAssetsPath+"/JavaScript"))
```

**Comment by igoper** [comment]
V7 StaticWeb ?

**Comment by kataras** [comment]
@Allendar and @igoper  the issue is fixed thanks for the report, upgrade and you're ready to go :)

We have some new features also, click [below](https://github.com/kataras/iris/blob/master/HISTORY.md#th-15-june-2017--v720) to read them!
