### ISSUE TITLE
Let's Encrypt  [HTTP Server] http: TLS handshake error

### ISSUE THREAD

**Issue by speedwheel** [iris-contrib/community-board#6]
Please answer these questions before submitting your issue. Thanks!

- [x] I have read the [_examples](https://github.com/kataras/iris/tree/master/_examples), [Contributing File](https://github.com/iris-contrib/community-board/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue was never [posted](https://github.com/iris-contrib/community-board/issues) before.

### What version of Go are you using, minimum 1.8 (`go version`)?

1.8.3

### What version of Iris are you using?

Version 10

### What did you do?

I am getting the following error when running the server with Let's Encrypt:

[HTTP Server] http: TLS handshake error from 79.113.170.105:51473: 429 urn:acme:error:rateLimited: Error creating new cert :: too many certificates already issued for exact set of domains: http://example.com

This started to show after few times after I stopped/started the server.

**Comment by kataras** [comment]
I did that [google search](https://www.google.com/search?q=golang+http%3A+TLS+handshake+error+from+79.113.170.105%3A51473%3A+429+urn%3Aacme%3Aerror%3ArateLimited%3A+Error+creating+new+cert+%3A%3A+too+many+certificates+already+issued+for+exact+set+of+domains%3A+http%3A%2F%2Fexample.com&oq=golang+http%3A+TLS+handshake+error+from+79.113.170.105%3A51473%3A+429+urn%3Aacme%3Aerror%3ArateLimited%3A+Error+creating+new+cert+%3A%3A+too+many+certificates+already+issued+for+exact+set+of+domains%3A+http%3A%2F%2Fexample.com&aqs=chrome..69i57j0l5.1350j0j7&sourceid=chrome&ie=UTF-8) and  it seems that is a regular issue by-design, it never happened to me before but you may need to read those to solve, it is not iris-specific , if you find a solution that worked for you please post it here, if you find something but you don't know how to do it, again post here in order to help you
